// Windissect exhaustive candidate class surface for bcp47mrm.dll.
// Experimental: declarations may contain unresolved PDB language ambiguities.
#pragma once

#include "windissect_abi.h"
#include "windissect_forwards.h"
#include "windissect_vcalls.h"
#include "windissect_calls.h"
#include "utilities/CLanguage.h"
#include "controls/LanguagesList.h"
#include "utilities/RegistryKey.h"
#include "utilities/Bcp47.h"
#include "utilities/ReadOnlyUserLanguagesRegistrar.h"
#include "utilities/ApplicationLanguagesRegistrar.h"
#include "values/RegistryMultiStringValue.h"
#include "utilities/PackageInfoHelper.h"
#include "utilities/CRegion.h"
#include "utilities/IApplicationLanguagesRegistrar.h"
#include "utilities/IRegistryKey.h"
#include "values/IRegistryMultiStringValue.h"
#include "utilities/IUserLanguagesRegistrar.h"
#include "values/ReadOnlyPendingUserDisplayLanguageRegistryValue.h"
#include "values/ReadOnlyPreviousUserDisplayLanguageRegistryValue.h"
#include "utilities/AppKey.h"
#include "controls/CLanguagesList.h"
#include "utilities/PendingUserDisplayLanguage.h"
#include "utilities/ReadOnlyUserLanguages.h"
#include "values/UserLanguageRegistryValue.h"
#include "utilities/UserLanguages.h"
#include "utilities/GlobUserModelAdapter.h"
#include "utilities/LocalStringsArray.h"
#include "utilities/HStringReference.h"
#include "controls/CLanguagesListFactory.h"
#include "utilities/String.h"
#include "utilities/StringReference.h"
